<!DOCTYPE html>
    <html>
    <head>
      <meta charset='utf-8'>
      <meta name='viewport' content='width=device-width'>
      <title>Privacy Policy</title>
      <style> body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding:1em; } </style>
    </head>
    <body>

<h1><strong>Privacy Policy</strong></h1>
<a href="https://meta-hi.uz/privacy/ru">На русском</a>
<h2><strong>1. </strong><strong>Introduction</strong></h2>
<p>This Privacy Policy sets out how we, Render Systems Inc.(&ldquo; <strong>Render Systems</strong>&rdquo;), use and protect your personal data that you provide to us, or that is otherwise obtained or generated by us, in connection with your use of our app <strong>MetaHi!</strong>. For the purposes of this Privacy Policy, <strong>&lsquo;we&rsquo;</strong>, <strong>&lsquo;us&rsquo;</strong> and <strong>&lsquo;our&rsquo;</strong> refers to <strong>MetaHi!</strong> and <strong>&lsquo;you&rsquo;</strong> refers to you, the user of the Services.</p>
<p><strong>1.1 Privacy Principles</strong></p>
<p><strong>MetaHi</strong> has fundamental principles when it comes to collecting and processing private data:</p>
<ul>
<li>We don't use your data to show you ads.</li>
<li>We only store the data that <strong>MetaHi!</strong> needs to function.</li>
</ul>
<p><strong>MetaHi </strong>function is to send HighFives to user&rsquo;s registered in app contacts, who are at a distance of no more than 25 meters, and last time location was sent no more than 1 hour</p>
<h2><strong>2. What Personal Data We Use</strong></h2>
<h3><strong>2.1. </strong><strong>Phone Number and Contacts</strong></h3>
<p><strong>MetaHi!</strong> uses phone numbers as unique identifiers. We ask your permission before syncing your contacts.</p>
<p>We store your up-to-date contacts in order to notify you as soon as one of your contacts signs up for <strong>MetaHi!</strong> and to properly display names in notifications. We only need the number and name (first and last) for this to work and store no other data about your contacts.</p>
<p>You can always stop syncing contacts or delete them from our servers and stop using our <strong>MetaHi!</strong> by clicking Delete Data and Exit action in App Menu.</p>
<h3><strong>2.2. Location Data</strong></h3>
<p><strong>MetaHi! </strong>collects <strong><em>location data</em></strong> to find people (from user contact list) around 25m, and provide opportunity to send HighFives (if other users farther more than 25m distance and time difference will be more than 1 hour, user can&rsquo;t see distance between them). <strong>MetaHi!</strong> collects location data when app is closed to calculate distance between more synchronized by time <strong>locations</strong>.</p>

<?php /*
    <strong>Terms &amp; Conditions</strong> <p>
                  By downloading or using the app, these terms will
                  automatically apply to you – you should make sure therefore
                  that you read them carefully before using the app. You’re not
                  allowed to copy or modify the app, any part of the app, or
                  our trademarks in any way. You’re not allowed to attempt to
                  extract the source code of the app, and you also shouldn’t try
                  to translate the app into other languages or make derivative
                  versions. The app itself, and all the trademarks, copyright,
                  database rights, and other intellectual property rights related
                  to it, still belong to Render Systems.
                </p> <p>
                  Render Systems is committed to ensuring that the app is
                  as useful and efficient as possible. For that reason, we
                  reserve the right to make changes to the app or to charge for
                  its services, at any time and for any reason. We will never
                  charge you for the app or its services without making it very
                  clear to you exactly what you’re paying for.
                </p> <p>
                  The MetaHi! app stores and processes personal data that
                  you have provided to us, to provide our
                  Service. It’s your responsibility to keep your phone and
                  access to the app secure. We therefore recommend that you do
                  not jailbreak or root your phone, which is the process of
                  removing software restrictions and limitations imposed by the
                  official operating system of your device. It could make your
                  phone vulnerable to malware/viruses/malicious programs,
                  compromise your phone’s security features and it could mean
                  that the MetaHi! app won’t work properly or at all.
                </p> <div><p>
                    The app does use third-party services that declare their
                    Terms and Conditions.
                  </p> <p>
                    Link to Terms and Conditions of third-party service
                    providers used by the app
                  </p> <ul><li><a href="https://policies.google.com/terms" target="_blank" rel="noopener noreferrer">Google Play Services</a></li><!----><li><a href="https://firebase.google.com/terms/analytics" target="_blank" rel="noopener noreferrer">Google Analytics for Firebase</a></li><li><a href="https://firebase.google.com/terms/crashlytics" target="_blank" rel="noopener noreferrer">Firebase Crashlytics</a></li><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----></ul></div> <p>
                  You should be aware that there are certain things that
                  Render Systems will not take responsibility for. Certain
                  functions of the app will require the app to have an active
                  internet connection. The connection can be Wi-Fi or provided
                  by your mobile network provider, but Render Systems
                  cannot take responsibility for the app not working at full
                  functionality if you don’t have access to Wi-Fi, and you don’t
                  have any of your data allowance left.
                </p> <p></p> <p>
                  If you’re using the app outside of an area with Wi-Fi, you
                  should remember that the terms of the agreement with your
                  mobile network provider will still apply. As a result, you may
                  be charged by your mobile provider for the cost of data for
                  the duration of the connection while accessing the app, or
                  other third-party charges. In using the app, you’re accepting
                  responsibility for any such charges, including roaming data
                  charges if you use the app outside of your home territory
                  (i.e. region or country) without turning off data roaming. If
                  you are not the bill payer for the device on which you’re
                  using the app, please be aware that we assume that you have
                  received permission from the bill payer for using the app.
                </p> <p>
                  Along the same lines, Render Systems cannot always take
                  responsibility for the way you use the app i.e. You need to
                  make sure that your device stays charged – if it runs out of
                  battery and you can’t turn it on to avail the Service,
                  Render Systems cannot accept responsibility.
                </p> <p>
                  With respect to Render Systems’s responsibility for your
                  use of the app, when you’re using the app, it’s important to
                  bear in mind that although we endeavor to ensure that it is
                  updated and correct at all times, we do rely on third parties
                  to provide information to us so that we can make it available
                  to you. Render Systems accepts no liability for any
                  loss, direct or indirect, you experience as a result of
                  relying wholly on this functionality of the app.
                </p> <p>
                  At some point, we may wish to update the app. The app is
                  currently available on Android &amp; iOS – the requirements for the 
                  both systems(and for any additional systems we
                  decide to extend the availability of the app to) may change,
                  and you’ll need to download the updates if you want to keep
                  using the app. Render Systems does not promise that it
                  will always update the app so that it is relevant to you
                  and/or works with the Android &amp; iOS version that you have
                  installed on your device. However, you promise to always
                  accept updates to the application when offered to you, We may
                  also wish to stop providing the app, and may terminate use of
                  it at any time without giving notice of termination to you.
                  Unless we tell you otherwise, upon any termination, (a) the
                  rights and licenses granted to you in these terms will end;
                  (b) you must stop using the app, and (if needed) delete it
                  from your device.
                </p> <p><strong>Changes to This Terms and Conditions</strong></p> <p>
                  We may update our Terms and Conditions
                  from time to time. Thus, you are advised to review this page
                  periodically for any changes. We will
                  notify you of any changes by posting the new Terms and
                  Conditions on this page.
                </p> <p>
                  These terms and conditions are effective as of 2021-12-13
                </p> <p><strong>Contact Us</strong></p> <p>
                  If you have any questions or suggestions about our
                  Terms and Conditions, do not hesitate to contact us
                  at Render Systems007@gmail.com.
                </p> */
                ?>
    </body>
    </html>
      